version: "3.5"
services:
  db:
    image: postgres:10.1-alpine
  web:
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "-t", "120", "--", "./base_site.sh"]
  game_bot:
    build:
      context: .
      dockerfile: DockerfileTest
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    command:
      [
        "./wait-for-it.sh",
        "web:${DJANGO_BIND_PORT}",
        "-t",
        "120",
        "--",
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "python",
        "manage.py",
        "game_bot",
      ]
  guild_helper_bot:
    build:
      context: .
      dockerfile: DockerfileTest
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    command:
      [
        "./wait-for-it.sh",
        "web:${DJANGO_BIND_PORT}",
        "-t",
        "120",
        "--",
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "python",
        "manage.py",
        "guild_helper_bot",
      ]
  tasks:
    build:
      context: .
      dockerfile: DockerfileTest
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t", "120",
        "--",
        "./wait-for-it.sh",
        "web:${PORT}",
        "-t",
        "120",
        "--",
        "./start-tasks.sh"
      ]

