# Generated by Django 3.0.1 on 2019-12-29 19:13
from typing import List

import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="ExchangeMessages",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.IntegerField(unique=True)),
                ("message_date", models.DateTimeField()),
                ("message_text", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="exchangemessages",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["message_date"], name="business_ex_message_9c613e_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangemessages",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["message_id"], name="business_ex_message_667caf_brin"
            ),
        ),
    ]
