# Generated by Django 3.0.1 on 2020-01-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_exchange', '0002_statsbyday'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsbyday',
            name='max_value_message_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsbyday',
            name='min_value_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
