# Generated by Django 3.0.1 on 2019-12-21 22:16

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("business_core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AuctionLot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auction_item", models.CharField(max_length=200)),
                ("message_id", models.CharField(max_length=30)),
                ("lot_id", models.IntegerField(unique=True)),
                ("seller_name", models.CharField(max_length=50)),
                ("seller_castle", models.CharField(max_length=30)),
                ("started_price", models.IntegerField()),
                ("message_date", models.DateTimeField()),
                ("quality", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("buyer_name", models.CharField(blank=True, max_length=50, null=True)),
                ("buyer_castle", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.IntegerField()),
                ("end_at", models.CharField(max_length=50)),
                ("real_time_end_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="business_core.Item")),
            ],
        ),
        migrations.CreateModel(
            name="AuctionLotBids",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("buyer_name", models.CharField(max_length=50)),
                ("buyer_castle", models.CharField(max_length=30)),
                (
                    "lot",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="business_auction.AuctionLot"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notify",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.CharField(max_length=20)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="business_core.Item")),
            ],
            options={"unique_together": {("item", "user")}},
        ),
        migrations.AddIndex(
            model_name="auctionlotbids",
            index=django.contrib.postgres.indexes.BrinIndex(fields=["date"], name="business_au_date_5ef83f_brin"),
        ),
        migrations.AddIndex(
            model_name="auctionlot",
            index=django.contrib.postgres.indexes.BrinIndex(fields=["lot_id"], name="business_au_lot_id_fdd5e5_brin"),
        ),
        migrations.AddIndex(
            model_name="auctionlot",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["message_date"], name="business_au_message_88cf8e_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionlot",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["finished_at"], name="business_au_finishe_246ea3_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionlot",
            index=django.contrib.postgres.indexes.BrinIndex(fields=["status"], name="business_au_status_67de0b_brin"),
        ),
    ]
