# Generated by Django 3.0.1 on 2019-12-26 23:50

import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("business_auction", "0002_auto_20191221_2252")]

    operations = [
        migrations.RemoveField(model_name="auctionlotbids", name="lot"),
        migrations.AlterUniqueTogether(name="notify", unique_together=None),
        migrations.RemoveField(model_name="notify", name="item"),
        migrations.RemoveIndex(model_name="auctionlot", name="business_au_finishe_246ea3_brin"),
        migrations.RemoveField(model_name="auctionlot", name="finished_at"),
        migrations.AlterField(model_name="auctionlot", name="message_id", field=models.IntegerField(unique=True)),
        migrations.AddIndex(
            model_name="auctionlot",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["message_id"], name="business_au_message_90e50f_brin"
            ),
        ),
        migrations.DeleteModel(name="AuctionLotBids"),
        migrations.DeleteModel(name="Notify"),
    ]
