# Generated by Django 3.0.6 on 2020-05-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0006_remove_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_id', models.FloatField()),
                ('forward_date', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('message_id', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('telegram_id', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDeposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_core.Item')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.Message')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.TelegramUser')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.TelegramUser'),
        ),
    ]
