# Generated by Django 3.1 on 2020-08-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_helper_bot', '0003_auto_20200829_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_id', models.FloatField()),
                ('forward_date', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('message_id', models.FloatField()),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('lvl', models.IntegerField()),
                ('combination', models.CharField(max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.hiddenmessage')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenHeadquarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('combination', models.CharField(max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.hiddenmessage')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.telegramuser')),
            ],
        ),
    ]
