# Generated by Django 3.1 on 2020-08-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_helper_bot', '0004_hiddenheadquarter_hiddenlocation_hiddenmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('alliance_atack_orders', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_helper_bot.guild')),
            ],
        ),
    ]
