# Generated by Django 3.1 on 2020-09-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_helper_bot', '0006_auto_20200901_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenheadquarter',
            name='combination',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hiddenlocation',
            name='combination',
            field=models.CharField(max_length=20),
        ),
    ]
