# Generated by Django 3.0 on 2019-12-08 01:53
from typing import List

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
        )
    ]
