# Generated by Django 3.0.1 on 2019-12-29 18:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("business_core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ExchangeItems",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
        )
    ]
