# Generated by Django 3.0.1 on 2019-12-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("business_core", "0005_auto_20191231_1926")]

    operations = [migrations.RemoveField(model_name="item", name="item_type")]
