name: Python Lint

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: 'chat_wars_database tests'
